name: CI

on:
  push:
    branches:
       - master
  workflow_dispatch:

env:
  NIXPKGS_ALLOW_BROKEN: 0

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.channel-branch }}
    strategy:
      matrix:
        channel-branch:
            - nixpkgs-unstable

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: cachix/install-nix-action@v15
      - name: Nix Version
        run: nix --version
      - name: Update lbstanza-bin
        run: |
          export NIX_PATH=nixpkgs=channel:${{ matrix.channel-branch }}
          nix-shell nix/update-lbstanza-bin/shell.nix --command run_and_commit
      - name: Build
        run: |
          export NIX_PATH=nixpkgs=channel:${{ matrix.channel-branch }}
          nix-build --show-trace
      - name: Run Version
        run: ./result/bin/stanza version
