name: Trigger Concourse on Push
on: [ push, workflow_dispatch ]
env:
  HOST: https://ci.jitx.com
  TEAM: main
  PIPELINE: lbstanza
  INSTVARS: vars.branch="${{ github.ref_name }}"
  TOKEN: ${{ secrets.CONCOURSE_WEBHOOK_TOKEN }}
jobs:
  trigger-push:
    runs-on: ubuntu-latest
    env:
      RESOURCE: git--lbstanza
    steps:
      - name: Trigger Concourse resource check
        run: |
          URL="${HOST}/api/v1/teams/${TEAM}/pipelines/${PIPELINE}/resources/${RESOURCE}/check/webhook?webhook_token=${TOKEN}&${INSTVARS}"
          echo Triggering: "${URL}"
          # ignore 404 errors if the branch pipeline doesn't exist in Concourse
          curl --silent --fail --show-error --location --request "POST" --url "${URL}" || true
